language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: clang
      sudo: required
    - os: linux
      dist: trusty
      compiler: gcc
      sudo: required
    - os: linux
      dist: trusty
      compiler: clang
      sudo: required
      env:
        - CMAKEOPT=-DSPOTIFY_JSON_USE_SSE42=OFF
        - VALGRIND=valgrind --leak-check=full
    - os: linux
      dist: trusty
      compiler: gcc
      sudo: required
      env:
        - CMAKEOPT=-DSPOTIFY_JSON_USE_SSE42=OFF
        - VALGRIND=valgrind --leak-check=full
    - os: osx
      compiler: clang
      env:
        - CMAKEOPT=-DBoost_NO_BOOST_CMAKE=ON
    - os: osx
      compiler: gcc
      env:
        - CMAKEOPT=-DBoost_NO_BOOST_CMAKE=ON

install: source .travis/install_${TRAVIS_OS_NAME}.sh

script:
  - BUILD_DIR="${TRAVIS_BUILD_DIR}/build_cmake"
  - mkdir -p ${BUILD_DIR} && cd ${BUILD_DIR}
  - cmake ${CMAKEOPT} .. && make
  - ${VALGRIND} ./test/spotify_json_test
